name: CD

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'AWS session token'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Unset variables
        run: |
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN

      #TODO refresh credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ github.event.inputs.token }}
          aws-region: us-east-1

      - name: Packer init
        run: packer init .

      - name: Validate packer template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer.pkr.hcl

      - name: Build artifact
        run: packer build packer.pkr.hcl

      - name: Get ami ID
        uses: sergeysova/jq-action@v2
        id: ami_id
        with:
          cmd: 'cat manifest.json | jq -r .builds[0].artifact_id |  cut -d':' -f2'

      - name: Setup AMI ID as terraform variable
        run: echo "AMI_ID=$(echo ${{steps.ami_id.outputs.value }})" >> GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: 'Terraform Init'
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform apply
        id: apply
        run: terraform apply -var="ami_id=${{ env.AMI_ID }}" -var="deployer-key=${{ secrets.deployer-key }}"

      # TODO: SSH into instance and build app with IP and run
